# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - pyggy

on:
    push:
        branches:
            - development

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - name: Set up Node.js version
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'

            - name: yarn install, start and build:client
            env:
              CI: ''
              run: |
                  yarn install --production=true
                  yarn install --cwd client
                  yarn build:client

            - name: 'Deploy to Azure Web App'
              uses: azure/webapps-deploy@v1
              with:
                  app-name: 'pyggy'
                  slot-name: 'production'
                  publish-profile: ${{ secrets.AzureAppService_PublishProfile_bf65deaaa0a4447d83fa3a286f136036 }}
                  package: .
